import {
  BadRequestException,
  ConflictException,
  Injectable,
  Logger,
  NotFoundException,
  OnModuleDestroy,
  OnModuleInit,
} from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { IsNull, Repository } from 'typeorm';
import { Payslip, PayslipStatus } from './payslip.entity';
import { EmployeeProfile } from './employee-profile.entity';
import { AttendanceService } from './attendance.service';
import { LeaveService } from './leave.service';
import { PayrollSettingsService } from './payroll-settings.service';
import { randomUUID } from 'crypto';
import { BulkGeneratePayslipDto, GeneratePayslipDto } from './dto/payslip.dto';

/** How often the scheduler checks whether today is the configured pay day. */
const SCHEDULER_TICK_MS = 60 * 60 * 1000;

@Injectable()
export class PayrollService implements OnModuleInit, OnModuleDestroy {
  private readonly logger = new Logger(PayrollService.name);
  private timer: ReturnType<typeof setInterval> | null = null;

  constructor(
    @InjectRepository(Payslip) private readonly repo: Repository<Payslip>,
    @InjectRepository(EmployeeProfile) private readonly empRepo: Repository<EmployeeProfile>,
    private readonly attendance: AttendanceService,
    private readonly leave: LeaveService,
    private readonly settings: PayrollSettingsService,
  ) {}

  /** Hourly tick — payslips are issued once, on the configured day. */
  onModuleInit() {
    this.timer = setInterval(() => {
      void this.tick();
    }, SCHEDULER_TICK_MS);
    setTimeout(() => void this.tick(), 15_000);
  }

  onModuleDestroy() {
    if (this.timer) clearInterval(this.timer);
  }

  private async tick() {
    try {
      const s = await this.settings.get();
      if (!s.auto_generate) return;
      // Catch-up friendly: any day on or after the pay day still triggers the
      // run, so a restart or downtime on the exact pay day never skips a month.
      if (new Date().getDate() < s.pay_day) return;
      const period = this.periodFor(s.period_offset);
      if (s.last_run_period === period) return;
      await this.runScheduled(period, 'payroll-scheduler', 'scheduled');
    } catch (err) {
      this.logger.error(`Automatic payroll run failed: ${(err as Error).message}`);
    }
  }

  private periodFor(offset: number) {
    const d = new Date();
    d.setDate(1);
    d.setMonth(d.getMonth() - offset);
    return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}`;
  }



  private enrich(p: Payslip) {
    return {
      ...p,
      employee_code: p.employee?.employee_code ?? null,
      employee_name: p.employee
        ? `${p.employee.first_name} ${p.employee.last_name}`.trim()
        : null,
      job_title: p.employee?.job_title ?? null,
      currency_code: p.currency?.code ?? null,
      currency_symbol: p.currency?.symbol ?? null,
      gross_pay: (
        Number(p.basic_salary) +
        Number(p.housing_allowance) +
        Number(p.transport_allowance) +
        Number(p.other_allowance) +
        Number(p.overtime_amount) +
        Number(p.bonus)
      ).toFixed(2),
      total_deductions: (
        Number(p.gosi_deduction) +
        Number(p.unpaid_leave_deduction) +
        Number(p.other_deduction)
      ).toFixed(2),
    };
  }

  async list(params: { period?: string; employee_id?: string; status?: string }) {
    const where: Record<string, unknown> = {};
    if (params.period) where.period = params.period;
    if (params.employee_id) where.employee_id = params.employee_id;
    if (params.status) where.status = params.status;
    where.deleted_at = IsNull();
    const rows = await this.repo.find({ where, order: { period: 'DESC', created_at: 'DESC' } });
    const items = rows.map((r) => this.enrich(r));

    // Totals are grouped per currency — payroll must never mix currencies.
    const byCurrency = new Map<string, { currency_code: string; net_total: number; count: number }>();
    for (const i of items) {
      const code = i.currency_code ?? '—';
      const e = byCurrency.get(code) ?? { currency_code: code, net_total: 0, count: 0 };
      e.net_total += Number(i.net_pay);
      e.count += 1;
      byCurrency.set(code, e);
    }
    return {
      items,
      summary: [...byCurrency.values()].map((e) => ({
        currency_code: e.currency_code,
        net_total: e.net_total.toFixed(2),
        payslips: e.count,
      })),
    };
  }

  async findOne(id: string) {
    const p = await this.repo.findOne({ where: { id, deleted_at: IsNull() } });
    if (!p) throw new NotFoundException('Payslip not found');
    return this.enrich(p);
  }

  async generate(
    dto: GeneratePayslipDto,
    actor: string,
    autoGenerated = false,
    workingDaysOverride?: number,
  ) {
    const employee = await this.empRepo.findOne({ where: { id: dto.employee_id } });
    if (!employee) throw new BadRequestException('Unknown employee — pick one from the list');
    if (!employee.salary_currency_id)
      throw new BadRequestException('This employee has no salary currency configured');
    if (employee.employment_status === 'terminated')
      throw new BadRequestException('Cannot run payroll for a terminated employee');

    const existing = await this.repo.findOne({
      where: { employee_id: dto.employee_id, period: dto.period, deleted_at: IsNull() },
    });
    if (existing)
      throw new ConflictException(
        `A payslip for ${dto.period} already exists for this employee (${existing.status}).`,
      );

    const settings = await this.settings.get();
    const att = await this.attendance.periodSummary(dto.employee_id, dto.period);
    const leave = await this.leave.periodLeave(dto.employee_id, dto.period);
    const overtimeRate = dto.overtime_rate ?? Number(settings.default_overtime_rate);
    const overtimeAmount = overtimeRate * att.overtime_hours;

    const gross =
      Number(employee.basic_salary) +
      Number(employee.housing_allowance) +
      Number(employee.transport_allowance) +
      Number(employee.other_allowance);

    // The daily rate uses the working days configured for the month, so public
    // holidays never inflate an employee's deduction.
    const workingDays = workingDaysOverride ?? (await this.settings.workingDaysFor(dto.period));
    const dailyRate = gross / Math.max(1, workingDays);

    // Only absences and leave beyond the entitlement cost the employee money.
    const deductibleDays = att.absent_days + leave.unpaid_leave_days;
    const unpaid = dailyRate * deductibleDays;

    const gosi =
      dto.gosi_deduction ?? (gross * Number(settings.default_gosi_percent)) / 100;

    const net =
      gross + overtimeAmount + (dto.bonus ?? 0) - unpaid - gosi - (dto.other_deduction ?? 0);
    if (net < 0) throw new BadRequestException('Deductions exceed the gross pay for this period');

    const saved = await this.repo.save(
      this.repo.create({
        employee_id: employee.id,
        period: dto.period,
        basic_salary: employee.basic_salary,
        housing_allowance: employee.housing_allowance,
        transport_allowance: employee.transport_allowance,
        other_allowance: employee.other_allowance,
        overtime_amount: overtimeAmount.toFixed(2),
        bonus: (dto.bonus ?? 0).toFixed(2),
        gosi_deduction: gosi.toFixed(2),
        unpaid_leave_deduction: unpaid.toFixed(2),
        other_deduction: (dto.other_deduction ?? 0).toFixed(2),
        net_pay: net.toFixed(2),
        currency_id: employee.salary_currency_id,
        worked_days: att.worked_days,
        absent_days: att.absent_days,
        working_days: workingDays,
        paid_leave_days: leave.paid_leave_days.toFixed(2),
        unpaid_leave_days: leave.unpaid_leave_days.toFixed(2),
        auto_generated: autoGenerated,
        overtime_hours: att.overtime_hours.toFixed(2),
        status: 'draft',
        notes: dto.notes ?? null,
        created_by: actor,
        updated_by: actor,
      }),
    );
    return this.findOne(saved.id);
  }

  /**
   * The scheduled run: one draft payslip for every active employee that does
   * not already have one for the period. Existing payslips are never touched.
   */
  async runScheduled(
    period: string | undefined,
    actor: string,
    trigger: 'scheduled' | 'manual' = 'manual',
  ) {
    const settings = await this.settings.get();
    const target = period ?? this.periodFor(settings.period_offset);
    const requestId = randomUUID();
    const calendar = await this.settings.resolveWorkingDays(target);
    this.logger.log(
      `[${requestId}] payroll run for ${target} using ${calendar.working_days} working days ` +
        `(source: ${calendar.source}${calendar.source_period ? ` ${calendar.source_period}` : ''})`,
    );
    const employees = await this.empRepo.find({
      where: {},
      order: { employee_code: 'ASC' },
    });

    const created: string[] = [];
    const skipped: { employee_code: string; reason: string }[] = [];
    for (const e of employees) {
      if (e.employment_status === 'terminated') continue;
      try {
        await this.generate(
          { employee_id: e.id, period: target },
          actor,
          true,
          calendar.working_days,
        );
        created.push(e.employee_code);
      } catch (err) {
        skipped.push({
          employee_code: e.employee_code,
          reason: err instanceof Error ? err.message : 'Could not generate payslip',
        });
      }
    }

    const summary = `${created.length} created, ${skipped.length} skipped`;
    await this.settings.markRun(target, summary);
    await this.settings.logRun({
      request_id: requestId,
      period: target,
      trigger_type: trigger,
      calendar_source: calendar.source,
      source_period: calendar.source_period,
      working_days: calendar.working_days,
      created_count: created.length,
      skipped_count: skipped.length,
      summary,
      actor,
    });
    this.logger.log(`[${requestId}] Payroll run for ${target}: ${summary}`);
    return { request_id: requestId, period: target, calendar, created, skipped, summary };
  }

  /**
   * Test generation: reports which month would be paid and whether the working
   * days come from that month's calendar, the last entered calendar data, or
   * the configured default — without writing a single payslip.
   */
  async previewRun(period: string | undefined, actor: string) {
    const settings = await this.settings.get();
    const target = period ?? this.periodFor(settings.period_offset);
    const requestId = randomUUID();
    const calendar = await this.settings.resolveWorkingDays(target);

    const employees = await this.empRepo.find({ where: {}, order: { employee_code: 'ASC' } });
    const eligible = employees.filter((e) => e.employment_status !== 'terminated');
    const wouldSkip: { employee_code: string; reason: string }[] = [];
    let wouldCreate = 0;
    for (const e of eligible) {
      const existing = await this.repo.findOne({
        where: { employee_id: e.id, period: target, deleted_at: IsNull() },
      });
      if (existing)
        wouldSkip.push({ employee_code: e.employee_code, reason: `Already ${existing.status}` });
      else if (!e.salary_currency_id)
        wouldSkip.push({ employee_code: e.employee_code, reason: 'No salary currency configured' });
      else wouldCreate += 1;
    }

    const summary = `${wouldCreate} would be created, ${wouldSkip.length} skipped`;
    await this.settings.logRun({
      request_id: requestId,
      period: target,
      trigger_type: 'test',
      calendar_source: calendar.source,
      source_period: calendar.source_period,
      working_days: calendar.working_days,
      created_count: wouldCreate,
      skipped_count: wouldSkip.length,
      dry_run: true,
      summary,
      actor,
    });
    return {
      request_id: requestId,
      period: target,
      dry_run: true,
      calendar,
      would_create: wouldCreate,
      would_skip: wouldSkip,
      summary,
    };
  }


  /**
   * Bulk run for every non-terminated employee holding the selected role.
   * Employees with an existing payslip for the period are skipped, so no
   * previously generated payroll data is ever rewritten.
   */
  async generateBulk(dto: BulkGeneratePayslipDto, actor: string) {
    const qb = this.empRepo
      .createQueryBuilder('e')
      .leftJoinAndSelect('e.user', 'user')
      .leftJoinAndSelect('user.role', 'role')
      .where('role.code = :code', { code: dto.role })
      .andWhere('e.employment_status != :terminated', { terminated: 'terminated' })
      .orderBy('e.employee_code', 'ASC');
    if (dto.department_id) qb.andWhere('e.department_id = :dep', { dep: dto.department_id });

    const employees = await qb.getMany();
    if (employees.length === 0)
      throw new BadRequestException('No active employees found for that role');

    const created: { employee_code: string; employee_name: string; net_pay: string }[] = [];
    const skipped: { employee_code: string; employee_name: string; reason: string }[] = [];

    for (const e of employees) {
      const name = `${e.first_name} ${e.last_name}`.trim();
      try {
        const slip = await this.generate(
          {
            employee_id: e.id,
            period: dto.period,
            overtime_rate: dto.overtime_rate,
            bonus: dto.bonus,
            gosi_deduction: dto.gosi_deduction,
            other_deduction: dto.other_deduction,
            notes: dto.notes,
          },
          actor,
        );
        created.push({ employee_code: e.employee_code, employee_name: name, net_pay: slip.net_pay });
      } catch (err) {
        skipped.push({
          employee_code: e.employee_code,
          employee_name: name,
          reason: err instanceof Error ? err.message : 'Could not generate payslip',
        });
      }
    }

    return {
      period: dto.period,
      role: dto.role,
      considered: employees.length,
      created,
      skipped,
    };
  }


  /** draft → approved → paid, with cancellation allowed before payment. */
  async setStatus(id: string, status: PayslipStatus, actor: string, cancelReason?: string) {
    const p = await this.repo.findOne({ where: { id, deleted_at: IsNull() } });
    if (!p) throw new NotFoundException('Payslip not found');
    const allowed: Record<PayslipStatus, PayslipStatus[]> = {
      draft: ['approved', 'cancelled'],
      approved: ['paid', 'cancelled'],
      paid: [],
      cancelled: [],
    };
    if (!allowed[p.status].includes(status))
      throw new BadRequestException(`A ${p.status} payslip cannot be moved to ${status}`);
    if (status === 'cancelled' && !cancelReason?.trim())
      throw new BadRequestException('A cancellation reason is required');
    p.status = status;
    if (status === 'cancelled') p.cancel_reason = cancelReason!.trim();
    p.paid_at = status === 'paid' ? new Date() : p.paid_at;
    p.updated_by = actor;
    await this.repo.save(p);
    return this.findOne(id);
  }

  /** Soft deletion — the row stays in the database with a deleted_at stamp. */
  async remove(id: string, actor: string) {
    const p = await this.repo.findOne({ where: { id, deleted_at: IsNull() } });
    if (!p) throw new NotFoundException('Payslip not found');
    if (p.status === 'approved')
      throw new BadRequestException(
        'An approved payslip cannot be deleted — it can only be cancelled or marked as paid',
      );
    if (p.status === 'paid') throw new BadRequestException('A paid payslip cannot be deleted');
    p.deleted_at = new Date();
    p.updated_by = actor;
    await this.repo.save(p);
    return { id, deleted: true };
  }
}
