apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# kubectl apply -k k8s/
resources:
  - configmap.yaml
  - secrets.yaml
  - mysql-pvc.yaml
  - mysql-statefulset.yaml
  - mysql-service.yaml
  - redis.yaml
  - backend-deployment.yaml
  - backend-service.yaml
  - frontend-deployment.yaml
  - frontend-service.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/part-of: erp
